### PR TITLE
chore: increase template quality for rest.mustache

### PR DESCRIPTION
**Pull request by dimakis**

### CODE REVIEW

**Review by jackdelahunt — APPROVED** [review]
Go no errors when running `make generate` LGTM 👍

**Review by rkpattnaik780 — APPROVED** [review]
Could generate the SDK without errors, but needed to use `sudo`, do you see that as a problem?

**Comment by dimakis** [comment]
> Could generate the SDK without errors, but needed to use `sudo`, do you see that as a problem?

@jackdelahunt did you need to do the same?
I don't have to run as `sudo`. It may be a permissions thing for the script but they should have the correct permissions. 
the CI runs without elevated privileges too. 🤔

**Comment by jackdelahunt** [comment]
I did not need to run it in sudo

**Comment by rkpattnaik780** [comment]
Could be something with my system @dimakis . LGTM!

**Pull request merged**
